how to make tomcat ami ?

FROM amazon-ami (base image)
RUN yum install java && \
wget tomcaturl.zip && \
unzip tomcat -d /opt/ 
RUN chmod 
RUN  rm -f zip 
RUN mv 
COPY shoppingcart.war /opt/tomcat/webapps/ 
EXPOSE 8080
CMD / ENTRYPOINT [/opt/tomcat/bin/startup.sh] 





apacheInstallation / staticWebsite 

FROM baseImage (ami)
RUN  yum update -y && \
yum install httpd -y 
